#!/usr/bin/env bash

set -e
set -u

script_name="$(basename "$0")"
script_dir="$(realpath "$(dirname "$0")")"

usage() {
  echo "${script_name}: usage: ${script_name} ARCHIVE_FILE" >&2
}

exit_with_error() {
  echo "${script_name}: error: $1" >&2
  usage
  exit 1
}

recieved_arguments="$#"
expected_arguments="1"

if [ "${recieved_arguments}" != "${expected_arguments}" ]; then
  exit_with_error "invalid number of arguments, expected \"${expected_arguments}\", recieved \"${recieved_arguments}\""
fi

backup_filepath="$1"

if [ ! -r "$backup_filepath" ]; then
  exit_with_error "invalid backup filepath \"$backup_filepath\""
fi

extract_variable() {
  grep "^${1}=" "${2}" | sed -E "s/^${1}=(.*)$/\1/"
}

database_username="$(extract_variable "MONGODB_USERNAME" "$script_dir/../.env")"
database_password="$(extract_variable "MONGODB_PASSWORD" "$script_dir/../.env")"
database_port="$(extract_variable "MONGODB_PORT" "$script_dir/../.env")"

create_container_temporary_file() {
  docker_compose_filepath="$1"

  docker-compose \
    --file "$docker_compose_filepath" \
    exec \
    mongo \
    mktemp
}

container_temporary_filepath="$(create_container_temporary_file "$script_dir/../docker-compose.yml")"

copy_host_file() {
  docker_compose_filepath="$1"
  host_filepath="$2"
  container_filepath="$3"

  docker-compose \
    --file "$docker_compose_filepath" \
    cp \
    "$host_filepath" "mongo:$container_filepath"
}

copy_host_file \
  "$script_dir/../docker-compose.yml" \
  "$backup_filepath" \
  "$container_temporary_filepath"

restore_container_archive() {
  docker_compose_filepath="$1"
  database_username="$2"
  database_password="$3"
  database_port="$4"
  container_filepath="$5"

  docker-compose \
    --file "$docker_compose_filepath" \
    exec \
    mongo \
    mongorestore \
    --username="$database_username" \
    --password="$database_password" \
    --port="$database_port" \
    --archive="$container_filepath"
}

restore_container_archive \
  "$script_dir/../docker-compose.yml" \
  "$database_username" \
  "$database_password" \
  "$database_port" \
  "$container_temporary_filepath"

remove_container_file() {
  docker_compose_filepath="$1"
  container_filepath="$2"

  docker-compose \
    --file "$docker_compose_filepath" \
    exec \
    mongo \
    rm \
    "$container_filepath"
}

remove_container_file \
  "$script_dir/../docker-compose.yml" \
  "$container_temporary_filepath"
